# ---------------------
# User Service 단독 테스트
# ---------------------
# 통신 확인 > 8082
#@host = http://localhost:8082
@host = http://localhost:8080
# 테스트할 아이디 (매번 바꾸거나 DB 초기화 후 사용)
@testCreatedId = 33
@testId = testuser10
@testPw = pwd123!@#
@testName = 테스트유저10
@testEmail = testuser1@test.com
@testPhone = 010-1010-1010
@testBirth = 2010-10-10

### 1. 회원가입 (인증 불필요) - 201 Created 확인
POST {{host}}/api/users/signup
Content-Type: application/json

{
  "loginId": "{{testId}}",
  "password": "{{testPw}}",
  "userName": "{{testName}}",
  "phoneNumber": "{{testPhone}}",
  "email": "{{testEmail}}",
  "birth": "{{testBirth}}"
}

### 2. 내 정보 조회 - 200 OK 확인
GET {{host}}/api/users/me
Content-Type: application/json
X-User-Id: {{testCreatedId}}

### 3. 내 정보 수정 - 200 OK 확인
# 이름과 이메일 변경
PATCH {{host}}/api/users/me
Content-Type: application/json
X-User-Id: {{testCreatedId}}

{
  "userName": "테스트유저10",
  "phoneNumber": "010-1010-1010",
  "email": "testuser10@test.com",
  "birth": "2010-10-10"
}

### 4. 비밀번호 변경 - 200 OK 확인
PUT {{host}}/api/users/me/password
Content-Type: application/json
X-User-Id: {{testCreatedId}}

{
  "currentPassword": "{{testPw}}",
  "newPassword": "new123!@#"
}

### 5. 주소 추가 - 201 Created 확인
POST {{host}}/api/users/me/addresses
Content-Type: application/json
X-User-Id: {{testCreatedId}}

{
  "addressName": "조선대학교 IT홀",
  "roadAddress": "광주광역시 동구 조선대5길 65",
  "addressDetail": "3층 IT홀",
  "isDefault": false
}

### 6. 주소 목록 조회 - 200 OK
GET {{host}}/api/users/me/addresses
Content-Type: application/json
X-User-Id: {{testCreatedId}}

> {%
    client.global.set("addressId", response.body[0].addressId);
%}

### 7. 주소 수정 - 200 OK 확인
PUT {{host}}/api/users/me/addresses/15
Content-Type: application/json
X-User-Id: {{testCreatedId}}

{
  "addressName": "조선대학교 중앙도서관",
  "roadAddress": "광주광역시 동구 조선대5길 19",
  "addressDetail": "2층 공감누리1",
  "isDefault": true
}

### 8. 주소 삭제 - 204 No Content 확인
DELETE {{host}}/api/users/me/addresses/16
X-User-Id: {{testCreatedId}}

### 9. 포인트 적립
POST {{host}}/api/internal/points
Content-Type: application/json

{
  "userCreatedId": {{testCreatedId}},
  "amount": 5000,
  "type": "EARN",
  "description": "관리자 지급 이벤트"
}

### 10. 포인트 사용 (잔액 부족 테스트)
POST {{host}}/api/internal/points
Content-Type: application/json

{
  "userCreatedId": {{testCreatedId}},
  "amount": 12000,
  "type": "USE",
  "description": "책 구매"
}

### 11. 내 포인트 내역 및 잔액 조회
GET {{host}}/api/users/me/points?page=0&size=10
X-User-Id: {{testCreatedId}}

### 12. 회원 탈퇴
DELETE {{host}}/api/users/me
X-User-Id: 16

### 13. 탈퇴 후 조회 확인
GET {{host}}/api/users/me
X-User-Id: 16

### 14. 휴면 해제 - 인증 코드 발송 요청
POST {{host}}/api/users/activate/send-code
Content-Type: application/json
X-User-Id: 1

### 15. 휴면 해제 - 인증 실패 (틀린 코드)
POST {{host}}/api/users/activate?code=000000
Content-Type: application/x-www-form-urlencoded
X-User-Id: 1

### 16. 휴면 해제 - 인증 성공 및 활성화
POST {{host}}/api/users/activate?code=643602
Content-Type: application/x-www-form-urlencoded
X-User-Id: 1

### 17. [Admin] 포인트 정책 등록 1
# Method: AMOUNT (정액)
POST {{host}}/api/admin/points/policies
Content-Type: application/json
X-User-Id: 33

{
  "policyName": "테스트 포인트 정책1",
  "policyType": "TEST1",
  "earnPoint": 100,
  "method": "AMOUNT"
}

### 18. [Admin] 포인트 정책 등록 2
# Method: RATIO (정률)
POST {{host}}/api/admin/points/policies
Content-Type: application/json
X-User-Id: 33

{
  "policyName": "테스트 포인트 정책2",
  "policyType": "TEST2",
  "earnPoint": 10.0,
  "method": "RATIO"
}

### 19. [Admin] 포인트 정책 전체 조회
GET {{host}}/api/admin/points/policies
Content-Type: application/json

### 20. [Admin] 포인트 정책 수정 (구매 적립률 5% -> 10% 상향)
PUT {{host}}/api/admin/points/policies/7
Content-Type: application/json
X-User-Id: 33

{
  "policyName": "테스트 포인트 정책1",
  "policyType": "TEST1",
  "earnPoint": 3.0,
  "method": "RATIO"
}

### 21. [Admin] 포인트 정책 삭제
DELETE {{host}}/api/admin/points/policies/5
X-User-Id: 33

### 22. [Admin] 전체 회원 목록 조회 (페이징)
GET {{host}}/api/admin/users?page=0&size=10
Content-Type: application/json
X-User-Id: {{testCreatedId}}

### 23. [Admin] 특정 회원 상세 조회
GET {{host}}/api/admin/users/{{testCreatedId}}
Content-Type: application/json
X-User-Id: {{testCreatedId}}

### 24. [Admin] 회원 상태 변경 (ACTIVE -> BANNED 정지)
PUT {{host}}/api/admin/users/{{testCreatedId}}/status
Content-Type: application/json
X-User-Id: {{testCreatedId}}

{
  "statusName": "BANNED"
}

### 25. [Admin] 회원 등급 변경 (GENERAL -> VIP)
PUT {{host}}/api/admin/users/{{testCreatedId}}/grade
Content-Type: application/json
X-User-Id: {{testCreatedId}}

{
  "gradeName": "PLATINUM"
}